version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(funcName)s %(lineno)d %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/hippocampai.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/hippocampai_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/hippocampai_json.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  # Application loggers
  src.qdrant_client:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.embedding_service:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_store:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_retriever:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_extractor:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_deduplicator:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_updater:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.importance_scorer:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.session_manager:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.memory_consolidator:
    level: INFO
    handlers: [console, file]
    propagate: false

  # Third-party loggers
  anthropic:
    level: WARNING
    handlers: [console, file]
    propagate: false

  qdrant_client:
    level: WARNING
    handlers: [console, file]
    propagate: false

  sentence_transformers:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
