# Prometheus Configuration for HippocampAI

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hippocampai-prod'
    environment: 'production'

# Alerting configuration (can be extended with Alertmanager)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # HippocampAI FastAPI Application
  - job_name: 'hippocampai-api'
    static_configs:
      - targets: ['hippocampai:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis Exporter (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 15s
