# HippocampAI Memory Assistant Configuration

# Application metadata
application:
  name: "HippocampAI Memory Assistant"
  version: "1.0.0"
  description: "Autonomous memory management system for LLM applications"

# Qdrant Collections Configuration
collections:
  personal_facts:
    description: "Personal facts, preferences, and goals"
    vector_size: 384
    distance: "Cosine"

  conversation_history:
    description: "Conversation context, events, and session summaries"
    vector_size: 384
    distance: "Cosine"

  knowledge_base:
    description: "General knowledge, habits, and information"
    vector_size: 384
    distance: "Cosine"

# Memory Management Settings
memory:
  # Importance scoring
  importance:
    min_score: 1
    max_score: 10
    default_score: 5
    critical_threshold: 9  # Memories above this rarely decay
    high_threshold: 7      # Memories above this decay slowly

  # Importance decay settings (by memory type)
  decay_rates:
    preference: 0.001    # Very slow decay
    fact: 0.002         # Slow decay
    goal: 0.003         # Moderate decay
    habit: 0.004        # Moderate-fast decay
    context: 0.008      # Fast decay
    event: 0.01         # Very fast decay

  # Deduplication settings
  deduplication:
    enabled: true
    similarity_threshold: 0.88
    auto_decide: true

  # Consolidation settings
  consolidation:
    enabled: true
    similarity_threshold: 0.85
    min_cluster_size: 2
    max_memories_per_run: 100
    frequency_days: 7
    memory_count_trigger: 50  # Trigger when user has >50 memories

# Retrieval Settings
retrieval:
  # Search limits
  default_limit: 10
  max_limit: 50

  # Smart search ranking weights
  smart_search:
    similarity_weight: 0.50
    importance_weight: 0.30
    recency_weight: 0.20
    max_access_boost: 0.2
    category_boost: 0.15
    candidates_multiplier: 3

  # Recency scoring
  recency:
    half_life_days: 30  # Exponential decay half-life

  # Context types
  context_types:
    work:
      categories: ["work", "finance"]
      boost: 0.15
    personal:
      categories: ["personal", "social", "health"]
      boost: 0.15
    casual:
      categories: ["personal", "social", "other"]
      boost: 0.15

# Session Management
sessions:
  timeout_minutes: 30
  max_messages: 100
  auto_summarize: true

  # Session importance calculation
  importance_base: 5
  long_session_threshold: 10    # messages
  very_long_threshold: 20       # messages
  decisions_bonus: 2

  tone_importance:
    "problem-solving": 1
    "planning": 1
    "learning": 0
    "casual": 0

# Extraction Settings
extraction:
  enabled: true
  min_confidence: 0.7
  batch_size: 10

# Performance Settings
performance:
  rate_limit:
    min_interval_ms: 100
    exponential_backoff: true
    max_backoff_seconds: 8

  retries:
    max_attempts: 2
    timeout_seconds: 30

  caching:
    embedding_cache_size: 1000
    ttl_seconds: 3600

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  levels:
    root: "INFO"
    qdrant_client: "INFO"
    embedding_service: "INFO"
    memory_store: "INFO"
    memory_retriever: "INFO"
    memory_extractor: "INFO"
    memory_deduplicator: "INFO"
    memory_updater: "INFO"
    importance_scorer: "INFO"
    session_manager: "INFO"
    memory_consolidator: "INFO"

  handlers:
    console:
      enabled: true
      level: "INFO"

    file:
      enabled: true
      level: "DEBUG"
      filename: "logs/hippocampai.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
      format: "json"  # or "text"

# Security Settings
security:
  validate_user_id: true
  sanitize_inputs: true
  max_text_length: 10000
  allowed_memory_types:
    - "preference"
    - "fact"
    - "goal"
    - "habit"
    - "event"
    - "context"
  allowed_categories:
    - "work"
    - "personal"
    - "learning"
    - "health"
    - "social"
    - "finance"
    - "other"
