#!/usr/bin/env python3
"""
Clean up ephemeral HippocampAI test collections from Qdrant.

The script supports several cleanup modes.

Default:
    Delete collections belonging to the current matrix job.

        QDRANT_TEST_NAMESPACE=ci-123456-3.11

    deletes:

        ci-123456-3.11_test_facts_abc
        ci-123456-3.11_test_prefs_def
        ci-123456-3.11_test_facts_advanced
        ci-123456-3.11_test_prefs_advanced


--run:
    Delete every collection belonging to the current GitHub workflow run.

        QDRANT_RUN_PREFIX=ci-123456-

    deletes collections belonging to:

        ci-123456-3.10_*
        ci-123456-3.11_*
        ci-123456-3.12_*


--all-stale:
    Delete known-safe legacy test collections.

    This is intended for scheduled/manual garbage collection and MUST NOT
    match production collection names.


--verify:
    Do not delete anything. Fail if matching collections still exist.


--list:
    Show CI/test-looking collections without deleting them.


Examples:

    python scripts/cleanup_qdrant_test_collections.py

    python scripts/cleanup_qdrant_test_collections.py --verify

    python scripts/cleanup_qdrant_test_collections.py --run

    python scripts/cleanup_qdrant_test_collections.py --run --verify

    python scripts/cleanup_qdrant_test_collections.py --all-stale

    python scripts/cleanup_qdrant_test_collections.py --list
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Iterable


# ---------------------------------------------------------------------------
# SAFETY
# ---------------------------------------------------------------------------
#
# These are collection prefixes/names known to be generated by HippocampAI
# tests.
#
# NEVER add a broad production-looking prefix here.
# ---------------------------------------------------------------------------

LEGACY_TEST_PREFIXES = (
    "test_facts_",
    "test_prefs_",
)

LEGACY_FIXED_NAMES = (
    "hippocampai_bitemporal_facts",
)

CI_PREFIX = "ci-"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Clean HippocampAI test collections from Qdrant."
    )

    parser.add_argument(
        "--run",
        action="store_true",
        help="Clean every collection belonging to QDRANT_RUN_PREFIX.",
    )

    parser.add_argument(
        "--all-stale",
        action="store_true",
        help="Clean known-safe legacy test collections.",
    )

    parser.add_argument(
        "--verify",
        action="store_true",
        help="Only verify that matching collections are gone.",
    )

    parser.add_argument(
        "--list",
        action="store_true",
        help="List CI/test collections without deleting anything.",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deleted without deleting anything.",
    )

    return parser.parse_args()


def get_client():
    """Create and return a Qdrant client."""

    try:
        from qdrant_client import QdrantClient
    except ImportError as exc:
        print("ERROR: qdrant-client is not installed.")
        raise SystemExit(1) from exc

    url = os.getenv("QDRANT_URL")
    api_key = os.getenv("QDRANT_API_KEY")

    if not url:
        print("ERROR: QDRANT_URL is not set.")
        raise SystemExit(1)

    try:
        client = QdrantClient(
            url=url,
            api_key=api_key,
            timeout=30,
        )

        # Force a connection immediately.
        client.get_collections()

        return client

    except Exception as exc:
        print(f"ERROR: Could not connect to Qdrant: {exc}")
        raise SystemExit(1) from exc


def get_collection_names(client) -> list[str]:
    """Return all collection names."""

    try:
        return sorted(
            collection.name
            for collection in client.get_collections().collections
        )

    except Exception as exc:
        print(f"ERROR: Could not list Qdrant collections: {exc}")
        raise SystemExit(1) from exc


def unique(values: Iterable[str]) -> list[str]:
    """Return sorted unique values."""

    return sorted(set(values))


def collections_for_current_job(
    collections: list[str],
) -> list[str]:
    """Find collections belonging to this matrix job."""

    namespace = os.getenv("QDRANT_TEST_NAMESPACE", "").strip()

    if not namespace:
        print("ERROR: QDRANT_TEST_NAMESPACE is not set.")
        raise SystemExit(1)

    # Test collection names are generated as:
    #
    #     {namespace}_{collection}
    #
    prefix = f"{namespace}_"

    return [
        name
        for name in collections
        if name.startswith(prefix)
    ]


def collections_for_current_run(
    collections: list[str],
) -> list[str]:
    """Find collections belonging to the entire GitHub workflow run."""

    run_prefix = os.getenv("QDRANT_RUN_PREFIX", "").strip()

    if not run_prefix:
        print("ERROR: QDRANT_RUN_PREFIX is not set.")
        raise SystemExit(1)

    # Additional safety.
    if not run_prefix.startswith(CI_PREFIX):
        print(
            "ERROR: Refusing run cleanup because "
            f"QDRANT_RUN_PREFIX={run_prefix!r} does not start with 'ci-'."
        )
        raise SystemExit(1)

    return [
        name
        for name in collections
        if name.startswith(run_prefix)
    ]


def stale_test_collections(
    collections: list[str],
) -> list[str]:
    """
    Find known-safe stale test collections.

    This catches collections created by older versions of the test suite
    before all collections were namespaced.
    """

    matches: list[str] = []

    for name in collections:
        if name.startswith(CI_PREFIX):
            matches.append(name)
            continue

        if name.startswith(LEGACY_TEST_PREFIXES):
            matches.append(name)
            continue

        if name in LEGACY_FIXED_NAMES:
            matches.append(name)

    return unique(matches)


def list_test_collections(
    collections: list[str],
) -> list[str]:
    """Return collections that look like HippocampAI test collections."""

    return stale_test_collections(collections)


def delete_collections(
    client,
    names: list[str],
    *,
    dry_run: bool,
) -> None:
    """Delete collections and fail if any deletion fails."""

    if not names:
        print("No matching Qdrant collections found.")
        return

    if dry_run:
        print(f"Would delete {len(names)} collection(s):")

        for name in names:
            print(f"  - {name}")

        return

    print(f"Deleting {len(names)} Qdrant collection(s):")

    failed: list[tuple[str, Exception]] = []

    for name in names:
        print(f"  DELETE {name}")

        try:
            client.delete_collection(
                collection_name=name,
                timeout=30,
            )

        except Exception as exc:
            failed.append((name, exc))
            print(f"    FAILED: {exc}")

    if failed:
        print()
        print("ERROR: Some Qdrant collections could not be deleted:")

        for name, exc in failed:
            print(f"  - {name}: {exc}")

        raise SystemExit(1)


def verify_deleted(
    client,
    expected_names: list[str],
) -> None:
    """Verify collections no longer exist."""

    if not expected_names:
        print("Nothing to verify.")
        return

    current = set(get_collection_names(client))

    remaining = [
        name
        for name in expected_names
        if name in current
    ]

    if remaining:
        print()
        print("ERROR: Qdrant cleanup verification failed.")
        print("The following collections still exist:")

        for name in remaining:
            print(f"  - {name}")

        raise SystemExit(1)

    print(
        f"Verified: all {len(expected_names)} "
        "matching collection(s) were deleted."
    )


def verify_current_scope(
    client,
    *,
    run_mode: bool,
) -> None:
    """
    Verify that no collections remain in the requested scope.

    Unlike verify_deleted(), this re-discovers the scope after cleanup.
    """

    collections = get_collection_names(client)

    if run_mode:
        remaining = collections_for_current_run(collections)
    else:
        remaining = collections_for_current_job(collections)

    if remaining:
        print("ERROR: Qdrant collections still remain:")

        for name in remaining:
            print(f"  - {name}")

        raise SystemExit(1)

    print("Qdrant cleanup verification successful: no collections remain.")


def main() -> int:
    args = parse_args()

    client = get_client()

    collections = get_collection_names(client)

    print(f"Qdrant currently contains {len(collections)} collection(s).")

    # ------------------------------------------------------------------
    # LIST
    # ------------------------------------------------------------------

    if args.list:
        matches = list_test_collections(collections)

        if not matches:
            print("No CI/test collections found.")
            return 0

        print(f"Found {len(matches)} CI/test collection(s):")

        for name in matches:
            print(f"  - {name}")

        return 0

    # ------------------------------------------------------------------
    # VERIFY
    # ------------------------------------------------------------------

    if args.verify:
        verify_current_scope(
            client,
            run_mode=args.run,
        )

        return 0

    # ------------------------------------------------------------------
    # DETERMINE CLEANUP SCOPE
    # ------------------------------------------------------------------

    if args.all_stale:
        targets = stale_test_collections(collections)

        print(
            "Running stale test collection garbage collection."
        )

    elif args.run:
        targets = collections_for_current_run(collections)

        print(
            "Cleaning collections belonging to the current "
            "GitHub workflow run."
        )

    else:
        targets = collections_for_current_job(collections)

        print(
            "Cleaning collections belonging to the current "
            "GitHub Actions matrix job."
        )

    targets = unique(targets)

    # ------------------------------------------------------------------
    # DELETE
    # ------------------------------------------------------------------

    delete_collections(
        client,
        targets,
        dry_run=args.dry_run,
    )

    if args.dry_run:
        return 0

    # ------------------------------------------------------------------
    # VERIFY DELETION
    # ------------------------------------------------------------------

    verify_deleted(
        client,
        targets,
    )

    print("Qdrant cleanup completed successfully.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
