name: Dependency Health

on:
  schedule:
    - cron: '0 6 * * 1'
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/dependency-health.yml'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project with tooling extras
        run: |
          python -m pip install --upgrade pip
          pip install .[core,dev,test,docs]

      - name: Run vulnerability scan
        run: pip-audit

      - name: Check license compliance
        run: liccheck -s liccheck.ini
